services:
# docker run -u zap -p 8080:8080 -i zaproxy/zap-stable zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=<api-key>
    zap:
        image: ghcr.io/zaproxy/zaproxy:stable
        container_name: zaproxy
        healthcheck:
            test: ["zap-cli", "status"]
            interval: 10s
            timeout: 5s
            retries: 10
        command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=supersecretapikey
        volumes:
            - ./zap.yaml:/zap/wrk/zap.yaml
        networks:
            - zap-tier

    coordinator:
        build: .
        depends_on:
            zap:
                condition: service_healthy
        volumes:
            - type: bind
              source: ./scanner_output
              target: /scanner_output
        environment:
            ZAP_HOST: zaproxy
            ZAP_PORT: 8080
            ZAP_API_KEY: supersecretapikey
        ports:
            - 8956:5000
        networks:
            - zap-tier

networks:
    zap-tier:

volumes:
  postgres_data: